const Order = require('../../domain/entities/order.entity');

class OrderService {
    constructor(orderRepository) { // ¡Depende de la interfaz!
        this.orderRepository = orderRepository;
    }

    async getAllOrders() {
        return this.orderRepository.getAll();
    }

    async getOrderById(id) {
        return this.orderRepository.getById(id);
    }

    async createOrder(orderData) {
        // Aquí podría haber lógica de negocio y validaciones
        // Calcular subtotal, descuento total y total
        let subtotal = 0;
        let totalDiscount = 0;

        if (orderData.items && Array.isArray(orderData.items)) {
            orderData.items.forEach(item => {
                const itemSubtotal = item.quantity * item.price;
                const itemDiscount = item.discount || 0;
                subtotal += itemSubtotal;
                totalDiscount += itemDiscount;
            });
        }

        const total = subtotal - totalDiscount;

        const orderEntity = new Order(
            null, // ID is null because it will be generated by the database
            orderData.orderNumber,
            orderData.customerName,
            orderData.customerEmail,
            orderData.items,
            subtotal,
            totalDiscount,
            total,
            orderData.status || 'pending',
            orderData.orderDate || new Date()
        );
        return this.orderRepository.create(orderEntity);
    }

    async updateOrder(id, orderData) {
        // Recalcular valores si se actualizan los items
        let subtotal = 0;
        let totalDiscount = 0;

        if (orderData.items && Array.isArray(orderData.items)) {
            orderData.items.forEach(item => {
                const itemSubtotal = item.quantity * item.price;
                const itemDiscount = item.discount || 0;
                subtotal += itemSubtotal;
                totalDiscount += itemDiscount;
            });
        }

        const total = subtotal - totalDiscount;

        const orderEntity = new Order(
            id,
            orderData.orderNumber,
            orderData.customerName,
            orderData.customerEmail,
            orderData.items,
            subtotal,
            totalDiscount,
            total,
            orderData.status,
            orderData.orderDate
        );
        return this.orderRepository.update(id, orderEntity);
    }

    async deleteOrder(id) {
        return this.orderRepository.delete(id);
    }
}

module.exports = OrderService;
